#define HW_MCU_STM32F405

#define HW_HAVE_LOW_SIDE_SHUNT
#define HW_HAVE_PWM_THREE_WIRE
#define HW_HAVE_PWM_GATE_FAULT
#define HW_HAVE_NTC_ON_PCB
#define HW_HAVE_NETWORK_EPCAN

#define HW_CLOCK_CRYSTAL_HZ		8000000U

#define HW_PWM_FREQUENCY_HZ		28571.f
#define HW_PWM_DEADTIME_NS		50.f		/* HL20N06D  */

#define HW_PWM_MINIMAL_PULSE		0.2f
#define HW_PWM_CLEARANCE_ZONE		5.0f
#define HW_PWM_SKIP_ZONE		2.0f
#define HW_PWM_BOOTSTRAP_RETENTION	100.f		/* MP6530 */

#define HW_ADC_SAMPLING_SEQUENCE	ADC_SEQUENCE__ABC_UTT_TXX

#define HW_ADC_REFERENCE_VOLTAGE	3.3f
#define HW_ADC_SHUNT_RESISTANCE		0.05f
#define HW_ADC_AMPLIFIER_GAIN		5.0f		/* TSV521A */

#define HW_ADC_VOLTAGE_R1		47000.f
#define HW_ADC_VOLTAGE_R2		4700.f

#define HW_NTC_PCB_TYPE			NTC_ON_VCC
#define HW_NTC_PCB_BALANCE		10000.f
#define HW_NTC_PCB_NTC0			10000.f
#define HW_NTC_PCB_TA0			25.f
#define HW_NTC_PCB_BETTA		3434.f		/* NCP15XH103F03RC */

#define GPIO_ADC_CURRENT_A		XGPIO_DEF3('A', 0, 0)
#define GPIO_ADC_CURRENT_B		XGPIO_DEF3('A', 1, 1)
#define GPIO_ADC_CURRENT_C		XGPIO_DEF3('A', 2, 2)
#define GPIO_ADC_VOLTAGE_U		XGPIO_DEF3('B', 1, 9)
#define GPIO_ADC_VOLTAGE_A		XGPIO_DEF3('C', 1, 11)
#define GPIO_ADC_VOLTAGE_B		XGPIO_DEF3('C', 3, 13)
#define GPIO_ADC_VOLTAGE_C		XGPIO_DEF3('C', 2, 12)
#define GPIO_ADC_NTC_PCB		XGPIO_DEF3('B', 0, 8)

#define GPIO_USART_TX			XGPIO_DEF4('B', 6, 0, 7)
#define GPIO_USART_RX			XGPIO_DEF4('B', 7, 0, 7)

#define GPIO_CAN_RX			XGPIO_DEF4('B', 8, 0, 9)
#define GPIO_CAN_TX			XGPIO_DEF4('B', 9, 0, 9)

#define GPIO_GATE_EN			XGPIO_DEF2('A', 11)
#define GPIO_GATE_FAULT			XGPIO_DEF2('B', 7)
#define GPIO_LED_ALERT			XGPIO_DEF2('C', 5)	/* have no LED */
#define GPIO_485_DE			XGPIO_DEF2('A', 3)
#define GPIO_DCDC_EN			XGPIO_DEF2('C', 15)

