#!/bin/bash

export CROSS="armv7m-none-eabi"
export MAKEOPTS="-j4"

for hwfile in hal/hw/*; do

	export HWREV=$(basename $hwfile .h)
	make $MAKEOPTS $1 || exit
done

make -C ../phobia -f Makefile.mingw ARCH=x86_64 $MAKEOPTS $1 || exit

test -z $1 || exit

zip -j9 /tmp/pmc-bundle-$(hg id -n).zip	\
	/tmp/pmc-*/*.bin /tmp/phobia/*/phobia.exe

