#!/bin/bash

export CROSS="armv7m-none-eabi"
export MAKEOPTS="-j4"

for hwfile in hal/hw/*; do

	export HWREV=$(basename $hwfile .h)
	make $MAKEOPTS $1 || exit
done

#make $MAKEOPTS HWREV=PESC1 $1 || exit

make -C ../phobia -f Makefile.mingw ARCH=i686   $MAKEOPTS $1 || exit
make -C ../phobia -f Makefile.mingw ARCH=x86_64 $MAKEOPTS $1 || exit

test -z $1 || exit

zip -j9 /tmp/pmc-bundle-$(hg id -n).zip	\
	/tmp/phobia/*/phobia-*.exe \
	/tmp/pmc-*/pmc-*.bin

