#!/bin/bash

export CROSS="armv7m-none-eabi"
export MAKEOPTS="-j8"

for hwfile in hal/hw/*; do

	export HWREV=$(basename $hwfile .h)
	make $MAKEOPTS $1					|| exit
done

make -C ../phobia -f Makefile.mingw ARCH=i686   $MAKEOPTS $1	|| exit
make -C ../phobia -f Makefile.mingw ARCH=x86_64 $MAKEOPTS $1	|| exit

export BUNDLE="/tmp/pmc-bundle-$(hg id -n)"

if [ -n "$1" ] && [ "$1" = "clean" ]; then

	rm -r -f $BUNDLE
	rm -f $BUNDLE.zip
	exit
fi

install -D -t $BUNDLE/ ../README.md 				|| exit
install -D -t $BUNDLE/doc ../doc/*.md 				|| exit

install -D -t $BUNDLE/firmware /tmp/pmc-*/pmc-*.bin 		|| exit
install -D -t $BUNDLE/phobia /tmp/phobia/*/phobia-*.exe 	|| exit

zip -rD -9 $BUNDLE.zip $BUNDLE

